site_name: DynDesign
theme:
    name: readthedocs
nav:
    - Installation: install.md
    - Overview: overview.md
    - Class Builder: class_builder.md
    - Dynamic Class Design: dynamic_class_design.md
    - Extended Communication Between Classes: extended_class_communication.md
    - Misc Utilities: misc_utilities.md
    - Tests: tests.md
    - License: license.md